### ISSUE TITLE
Building for ARM or Unix x64

### ISSUE THREAD

**Issue by jwinarske** [linino/bathos-mcuio#1]
Building with either versatile_defaultconfig, or unix_defaultconfig generates same build break.  In the case of unix_defaultconfig version_data.o is of type "elf64-little".

lilsprout@jollygreen:~/bathos-mcuio$ make
 make -f Makefile.kconfig silentoldconfig
 make[1]: Entering directory `/home/joel/bathos-mcuio'
 make -f scripts/Makefile.build obj=scripts/basic
 make -f scripts/Makefile.build obj=scripts/kconfig Makefile.kconfig
 make[2]: Nothing to be done for `Makefile.kconfig'.
 make -f scripts/Makefile.build obj=scripts/kconfig silentoldconfig
 mkdir -p include/generated
 scripts/kconfig/conf -s /home/lilsprout/bathos-mcuio/Kconfig
 make[1]: Leaving directory `/home/lilsprout/bathos-mcuio'
 export CC=arm-none-eabi-gcc OBJDUMP=arm-none-eabi-objdump OBJCOPY=arm-none-eabi-objcopy ; \
     scripts/gen_version_data f4c7d82+ $(scripts/get_bin_format) \
     version_data.o
 arm-none-eabi-objcopy: Unable to recognise the format of the input file `version_data.o'
 make: *** [version_data.o] Error 1
 lilsprout@jollygreen:~/bathos-mcuio$ arm-none-eabi-objdump -D version_data.o

 version_data.o:     file format elf32-little

 arm-none-eabi-objdump: can't disassemble for architecture UNKNOWN!

 lilsprout@jollygreen:~/bathos-mcuio$

**Comment by colosimo** [comment]
Hi Joel
I know there is this issue with some arm toolchains, and actually it seems a bug of the compiler itself. We found a workaround, I have to ask my colleague about it. First of all, can you please tell me which toolchain are you using?
Thanks

**Comment by jwinarske** [comment]
gcc-arm-none-eabi (4.8.2-14ubuntu1+6) 
amd64 flavor
http://packages.ubuntu.com/trusty/devel/gcc-arm-none-eabi

**Comment by ciminaghi** [comment]
On Mon, May 11, 2015 at 09:32:53AM -0700, Joel Winarske wrote:
> Building with either versatile_defaultconfig, or unix_defaultconfig generates same build break.  In the case of unix_defaultconfig version_data.o is of type "elf64-little".
> 
> lilsprout@jollygreen:~/bathos-mcuio$ make
>  make -f Makefile.kconfig silentoldconfig
>  make[1]: Entering directory `/home/joel/bathos-mcuio'
>  make -f scripts/Makefile.build obj=scripts/basic
>  make -f scripts/Makefile.build obj=scripts/kconfig Makefile.kconfig
>  make[2]: Nothing to be done for `Makefile.kconfig'.
>  make -f scripts/Makefile.build obj=scripts/kconfig silentoldconfig
>  mkdir -p include/generated
>  scripts/kconfig/conf -s /home/lilsprout/bathos-mcuio/Kconfig
>  make[1]: Leaving directory `/home/lilsprout/bathos-mcuio'
>  export CC=arm-none-eabi-gcc OBJDUMP=arm-none-eabi-objdump OBJCOPY=arm-none-eabi-objcopy ; \
>      scripts/gen_version_data f4c7d82+ $(scripts/get_bin_format) \
>      version_data.o
>  arm-none-eabi-objcopy: Unable to recognise the format of the input file `version_data.o'
>  make: *** [version_data.o] Error 1
>  lilsprout@jollygreen:~/bathos-mcuio$ arm-none-eabi-objdump -D version_data.o
> 
>  version_data.o:     file format elf32-little
> 
>  arm-none-eabi-objdump: can't disassemble for architecture UNKNOWN!
> 
>  lilsprout@jollygreen:~/bathos-mcuio$
>
bathos-mcuio shipped with lininoio releases presently builds for atmega only,
as far as I know (Aurelio knows better).
I've set up a branch which builds for atmega and arm (freescale kl25z),
but that's experimental: on arm, it only supports basic stuff such as
periodic timer, uart, gpios and usb on a freescale kl25z board. No test has
been done on atmega yet, so it should build without warnings, but it might
not work.
In case you're interested in the code, you can find it on my personal github
(git@github.com:ciminaghi/bathos-mcuio.git, branch atmega-kl25z), it should
build with yun_defconfig (for the atmega) and freedog_basic_defconfig
(for the freescale).

I'm planning to get unix and maybe versatile to build in the future.

The particular problem you've found (Unable to recognise the format of the
input file `version_data.o') seems due to a bug in the linker, which refuses
to link files obtained via objcopy -O binary (we use objcopy to convert the
version string directly to a binary form without calling the C compiler).
As far as I've understood, the bug should be fixed some time in the future,
so I just added a (hopefully) temporary workaround while working on my
atmega + arm branch, see 

https://github.com/ciminaghi/bathos-mcuio/blob/atmega-kl25z/scripts/arm_fix_elf

for more details. I guess you could use the same trick for other archs, or
maybe you can find a better workaround.
If you succeed, maybe you could send us patches to get unix and versatile
to build at least (and maybe even to work :-)
Anyway, I'm not sure this is the only problem you'll face when trying to
build for unix and versatile, so be prepared. Of course you can ask
questions and we'll be glad to help you.

Thanks and regards
Davide

**Comment by dciminaghi** [comment]
On Mon, May 11, 2015 at 10:35:53AM -0700, Davide Ciminaghi wrote:
> On Mon, May 11, 2015 at 09:32:53AM -0700, Joel Winarske wrote:
> > Building with either versatile_defaultconfig, or unix_defaultconfig generates same build break.  In the case of unix_defaultconfig version_data.o is of type "elf64-little".
> > 
> > lilsprout@jollygreen:~/bathos-mcuio$ make
> >  make -f Makefile.kconfig silentoldconfig
> >  make[1]: Entering directory `/home/joel/bathos-mcuio'
> >  make -f scripts/Makefile.build obj=scripts/basic
> >  make -f scripts/Makefile.build obj=scripts/kconfig Makefile.kconfig
> >  make[2]: Nothing to be done for `Makefile.kconfig'.
> >  make -f scripts/Makefile.build obj=scripts/kconfig silentoldconfig
> >  mkdir -p include/generated
> >  scripts/kconfig/conf -s /home/lilsprout/bathos-mcuio/Kconfig
> >  make[1]: Leaving directory `/home/lilsprout/bathos-mcuio'
> >  export CC=arm-none-eabi-gcc OBJDUMP=arm-none-eabi-objdump OBJCOPY=arm-none-eabi-objcopy ; \
> >      scripts/gen_version_data f4c7d82+ $(scripts/get_bin_format) \
> >      version_data.o
> >  arm-none-eabi-objcopy: Unable to recognise the format of the input file `version_data.o'
> >  make: *** [version_data.o] Error 1
> >  lilsprout@jollygreen:~/bathos-mcuio$ arm-none-eabi-objdump -D version_data.o
> > 
> >  version_data.o:     file format elf32-little
> > 
> >  arm-none-eabi-objdump: can't disassemble for architecture UNKNOWN!
> > 
> >  lilsprout@jollygreen:~/bathos-mcuio$
> >
> bathos-mcuio shipped with lininoio releases presently builds for atmega only,
> as far as I know (Aurelio knows better).
> I've set up a branch which builds for atmega and arm (freescale kl25z),
> but that's experimental: on arm, it only supports basic stuff such as
> periodic timer, uart, gpios and usb on a freescale kl25z board. No test has
> been done on atmega yet, so it should build without warnings, but it might
> not work.
> In case you're interested in the code, you can find it on my personal github
> (git@github.com:ciminaghi/bathos-mcuio.git, branch atmega-kl25z), it should
> build with yun_defconfig (for the atmega) and freedog_basic_defconfig
> (for the freescale).
> 
> I'm planning to get unix and maybe versatile to build in the future.
> 
> The particular problem you've found (Unable to recognise the format of the
> input file `version_data.o') seems due to a bug in the linker, which refuses
> to link files obtained via objcopy -O binary (we use objcopy to convert the

sorry, I meant -I binary -O elf32-whatever, of course.

Davide

**Comment by jwinarske** [comment]
Your branch isn't building for me with freedog_basic_defconfig.  It generated the gpio object files as elf32-little.

...
for p in $(seq 0 $((3 - 1))) ; do \
		offs=$(($p * 64)) \
		ngpios=$(scripts/get_port_ngpios $p 64 160); \
		scripts/gen_gpios_names $(scripts/get_bin_format) tasks/arm-freedog-gpios.cfg \
		$p $offs $ngpios tasks/arm-freedog-gpios-names_$p.o ; \
	done
arm-none-eabi-ld -r  tasks/arm-freedog-gpios-names_0.o  tasks/arm-freedog-gpios-names_1.o  tasks/arm-freedog-gpios-names_2.o -o tasks/arm-freedog-gpios-names.o
arm-none-eabi-ld: unknown architecture of input file `tasks/arm-freedog-gpios-names_0.o' is incompatible with arm output
arm-none-eabi-ld: unknown architecture of input file `tasks/arm-freedog-gpios-names_1.o' is incompatible with arm output
arm-none-eabi-ld: unknown architecture of input file `tasks/arm-freedog-gpios-names_2.o' is incompatible with arm output
make: *** [tasks/arm-freedog-gpios-names.o] Error 1
lilsprout@jollygreen:~/_bathos-mcuio-kl25z$ arm-none-eabi-objdump -D ./tasks/arm-freedog-gpios-names_0.o

./tasks/arm-freedog-gpios-names_0.o:     file format elf32-little

arm-none-eabi-objdump: can't disassemble for architecture UNKNOWN!

lilsprout@jollygreen:~/_bathos-mcuio-kl25z$

**Comment by jwinarske** [comment]
This resolved the build issue.
export ARCH=arm

**Comment by ciminaghi** [comment]
On Tue, May 12, 2015 at 09:04:41PM -0700, Joel Winarske wrote:
> This resolved the build issue.
> export ARCH=arm
>
mmm, that shouldn't be needed. I think I'll tell make to export ARCH,
since ARCH should come from CONFIG_ARCH, we should not depend on what is in
the environment.

Thanks a lot
Davide

**Comment by dciminaghi** [comment]
On Tue, May 12, 2015 at 09:04:40PM -0700, Joel Winarske wrote:
> This resolved the build issue.
> export ARCH=arm
>
I've just pushed a commit which exports ARCH, branch atmega-kl25z as usual.

Thanks again
Davide

**Comment by jwinarske** [comment]
Hi Davide,

Still seeing a problem with these files:
scripts/gen_gpios_names
scripts/get_bin_format

scripts/gen_gpios_names
...
[ "$ARCH" = "arm" ] && BARG="-B arm"
echo ARCH=$ARCH
echo BARG=$BARG

outputs:
ARCH=
BARG=

scripts/get_bin_format
...
echo CC=$CC
echo OBJDUMP=$OBJDUMP
$CC -c -o $src.o $src  || ret=1

outputs:
CC=
OBJDUMP=

**Comment by dciminaghi** [comment]
On Wed, May 13, 2015 at 08:02:11AM -0700, Joel Winarske wrote:
> Hi Davide,
> 
> Still seeing a problem with these files:
> scripts/gen_gpios_names
> scripts/get_bin_format
> 
> scripts/gen_gpios_names
> ...
> [ "$ARCH" = "arm" ] && BARG="-B arm"
> echo ARCH=$ARCH
> echo BARG=$BARG
> 
> outputs:
> ARCH=
> BARG=
> 
> scripts/get_bin_format
> ...
> echo CC=$CC
> echo OBJDUMP=$OBJDUMP
> $CC -c -o $src.o $src  || ret=1
> 
> outputs:
> CC=
> OBJDUMP=
>
I'm sorry, I can't understand what you're trying to do exactly. Are you saying
that exporting ARCH from the Makefile is not working ? Do you still have
build errors ?

How are you running the scripts ? They're intended to be called by the
Makefile, so they expect CC, ARCH, OBJDUMP, ... to be in the environment.

Davide

**Comment by jwinarske** [comment]
Just cloned atmega-kl25z.  It builds fine for me without changes.  I'm using:
<freedog_basic_defconfig -> set CONFIG_CROSS_COMPILE=arm-none-eabi->
make clean
make freedog_basic_defconfig
make

Is there a goal to enable building of all configs moving forward?
What's the planned master branch?

**Comment by ciminaghi** [comment]
On Thu, May 14, 2015 at 09:16:11PM -0700, Joel Winarske wrote:
> Just cloned atmega-kl25z.  It builds fine for me without changes.  I'm using:
> <freedog_basic_defconfig -> set CONFIG_CROSS_COMPILE=arm-none-eabi->
> make clean
> make freedog_basic_defconfig
> make
> 
> Is there a goal to enable building of all configs moving forward?

yes that's (one of) my goal(s).

I'm not sure versatile will be included. I was looking at it yesterday,
maybe it will become just another arm machine (under arch-arm/).
I'd also like to add the lpc1768, which has an ethernet port, with the
goal of using raw ethernet packets as the mcuio transport (high speed
gpios over ethernet for example). I'd also like to add the original lpcs
supported by bathos (lpc1343, lpc2104), which I removed when the new
arch-arm was created. Many cortex-mX should have a lot of code in common,
so that shouldn't be too hard.


> What's the planned master branch?
> 

I still have no master branch, what I do is usually taken by my colleague
Aurelio (if he thinks it is ok) and goes to the "official" lininoio
bathos-mcuio repository:

https://github.com/linino/bathos-mcuio

The master branch there is still atmega32u4, as far as I know.
My work on the kl25z and the arm architecture hasn't been pulled yet.

Regards
Davide
